name: chess_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_svg: ^2.2.3
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - fonts/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: fonts/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: fonts/GoogleSans-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/GoogleSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/GoogleSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/GoogleSans-BoldItalic.ttf
          style: italic
          weight: 700

    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Inter-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Inter-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Inter-BoldItalic.ttf
          style: italic
          weight: 700
